# POST http://localhost:5173/article/create
# content-type: application/json

# {
#     "writer" : "deneme5",
#     "title" : "sudan",
#     "body" : "sudan body text",
#     "image": "https://fastly.picsum.photos/id/828/200/200.jpg?hmac=XDYHUvU1Ha9LQrkNk3svII_91vwnQqo8C0yWMqCt6V8"

# }

GET http://localhost:5173/article/findAll

# GET http://localhost:5173/article/findOne/65f3f281de11ba9959a05f08

# DELETE http://localhost:5173/article/deleteOne/65f4042c7501b177f394383b

# PATCH http://localhost:5173/article/updateOne/65f404887501b177f3943841
# content-type : application/json

# {
#     "writer": "sinan"
# }

 