# POST http://localhost:5173/auth/create
# content-type: application/json

# {
#     "username" : "denemeuser",
#     "password" : "denemepassword"

# }

#GET http://localhost:5173/auth/findAll

#GET http://localhost:5173/authfindOne/65f2eacabc769af788e86746

#DELETE http://localhost:5173/authdeleteOne/65f2eacabc769af788e86746

# PATCH http://localhost:5173/auth/updateOne/65f2ee8851cff61ca1b53aa9
# content-type : application/json

# {
#     "username": "ayhan",
#     "password": "ayhan12"
# }

 